[2024-12-04 05:45:08,770] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: KPIs_for_5_Minutes.fetch_master_Data 2024-12-04T05:40:00+00:00 [queued]>
[2024-12-04 05:45:08,802] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: KPIs_for_5_Minutes.fetch_master_Data 2024-12-04T05:40:00+00:00 [queued]>
[2024-12-04 05:45:08,802] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-04 05:45:08,803] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-04 05:45:08,804] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-04 05:45:08,874] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_master_Data> on 2024-12-04T05:40:00+00:00
[2024-12-04 05:45:08,880] {standard_task_runner.py:52} INFO - Started process 868 to run task
[2024-12-04 05:45:08,885] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'KPIs_for_5_Minutes', 'fetch_master_Data', '2024-12-04T05:40:00+00:00', '--job-id', '467', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Kpi_dags/main.py', '--cfg-path', '/tmp/tmp9hu2te7i', '--error-file', '/tmp/tmp49g9iv36']
[2024-12-04 05:45:08,886] {standard_task_runner.py:77} INFO - Job 467: Subtask fetch_master_Data
[2024-12-04 05:45:09,022] {logging_mixin.py:104} INFO - Running <TaskInstance: KPIs_for_5_Minutes.fetch_master_Data 2024-12-04T05:40:00+00:00 [running]> on host ca28183b9a80
[2024-12-04 05:45:09,362] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Rule Manager
AIRFLOW_CTX_DAG_ID=KPIs_for_5_Minutes
AIRFLOW_CTX_TASK_ID=fetch_master_Data
AIRFLOW_CTX_EXECUTION_DATE=2024-12-04T05:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-04T05:40:00+00:00
[2024-12-04 05:45:09,364] {main.py:98} INFO - Fetching data from master db and storing excel between 2024-12-04 05:40:00 and 2024-12-04 05:45:00
[2024-12-04 05:45:09,365] {main.py:23} INFO - Connecting to database...
[2024-12-04 05:45:09,395] {base.py:69} INFO - Using connection to: id: master_table_conn. Host: 10.10.18.92, Port: 5432, Schema: landing_zone, Login: Chakradhar, Password: ***, extra: {}
[2024-12-04 05:45:09,766] {main.py:26} INFO - Connected successfully...
[2024-12-04 05:45:09,859] {main.py:106} INFO - data fetched successfully from master db
[2024-12-04 05:45:09,864] {main.py:108} INFO - data stored successfully
[2024-12-04 05:45:09,865] {python.py:151} INFO - Done. Returned value was: None
[2024-12-04 05:45:09,886] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=KPIs_for_5_Minutes, task_id=fetch_master_Data, execution_date=20241204T054000, start_date=20241204T054508, end_date=20241204T054509
[2024-12-04 05:45:09,999] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04 05:45:10,012] {local_task_job.py:151} INFO - Task exited with return code 0
