[2024-11-21 11:02:19,808] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-21T10:57:13.983902+00:00 [queued]>
[2024-11-21 11:02:19,958] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-21T10:57:13.983902+00:00 [queued]>
[2024-11-21 11:02:19,960] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-11-21 11:02:20,004] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-11-21 11:02:20,013] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-11-21 11:02:20,397] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-21T10:57:13.983902+00:00
[2024-11-21 11:02:20,405] {standard_task_runner.py:52} INFO - Started process 396 to run task
[2024-11-21 11:02:20,409] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'kpi_calculation_pipeline', 'fetch_data', '2024-11-21T10:57:13.983902+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_injestion_dag/bazefield_kpi_calculation.py', '--cfg-path', '/tmp/tmpem_6mv4p', '--error-file', '/tmp/tmp_a8c9794']
[2024-11-21 11:02:20,416] {standard_task_runner.py:77} INFO - Job 61: Subtask fetch_data
[2024-11-21 11:02:20,757] {logging_mixin.py:104} INFO - Running <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-21T10:57:13.983902+00:00 [running]> on host 1b505405454d
[2024-11-21 11:02:21,485] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=kpi_calculation_pipeline
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-21T10:57:13.983902+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-21T10:57:13.983902+00:00
[2024-11-21 11:02:21,621] {base.py:69} INFO - Using connection to: id: bazefield_api. Host: https://idcc.jsw.in, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2024-11-21 11:02:21,634] {http.py:140} INFO - Sending 'GET' to url: https://idcc.jsw.in/Bazefield.Services/api/objects/timeseries/aggregated?objectIds=11002CC087CEB000,11003170EE0EB000,11003170FD4EB000,110031710ACEB000,110031717B8EB000,11003171B24EB000,11003171C00EB000,11003171DD8EB000,11003171EB8EB000,110031733E0EB000,110031734C4EB000,110031735B4EB000,11003176A54EB000,11003177284EB000,1100317739CEB000,110031720D0EB000,11003173790EB000,11003173A68EB000,110031758CCEB000,11003176424EB000,11003176520EB000,11003176620EB000,11003176834EB000,11003173004EB000,110031730FCEB000,11003175A08EB000,11003175C24EB000,11003175D24EB000,11003175E94EB000,11003175FB4EB000,11003176324EB000,110031775B8EB000,11003171260EB000,11003171344EB000,11003171438EB000,11003171520EB000,11003171608EB000,110031716F0EB000,1100317188CEB000,11003171960EB000,11003171A48EB000,11003171CF0EB000,11003171FF0EB000,1100317369CEB000,110031723ACEB000,11003172488EB000,1100317257CEB000,11003172664EB000,11003172750EB000,1100317283CEB000,11003172928EB000,11003175B1CEB000,11003176724EB000,11003176938EB000,110031774A8EB000,110031721D0EB000,110031722CCEB000,11003172A20EB000,11003172B08EB000,11003172BFCEB000,11003173894EB000,11003173988EB000,1100317621CEB000,11003176C94EB000,11003176DCCEB000,11003177174EB000,11003172CE4EB000,11003172DD8EB000,11003172F0CEB000,11003173B58EB000,11003173C54EB000,11003173D50EB000,11003174760EB000,11003175698EB000,11003176B68EB000,11003176F14EB000,1100317705CEB000,11003174B6CEB000,11003175278EB000,11003175374EB000,110031755A0EB000,11003173F2CEB000,11003174C68EB000,11003174D68EB000,11003174F64EB000,11003175060EB000,11003175178EB000,11003175480EB000,110031760C4EB000,11003173E34EB000,11003174030EB000,11003174660EB000,1100317487CEB000,11003174978EB000,11003174A7CEB000,110031731F0EB000,110031732F0EB000,1100317411CEB000,11003174214EB000,11003174324EB000,1100317443CEB000,11003174544EB000,11003174E6CEB000,110031757B4EB000&points=ActivePower&aggregates=TIMEAVERAGE&from=2024-11-21T10:00:00Z&to=2024-11-21T10:59:59Z&interval=10m&format=json
[2024-11-21 11:02:23,046] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_injestion_dag/bazefield_kpi_calculation.py", line 280, in fetch_active_power_kpi
    'v': time_series['v'],
KeyError: 'v'
[2024-11-21 11:02:23,054] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=kpi_calculation_pipeline, task_id=fetch_data, execution_date=20241121T105713, start_date=20241121T110219, end_date=20241121T110223
[2024-11-21 11:02:23,767] {local_task_job.py:151} INFO - Task exited with return code 1
